name: Static Website Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run Static Website Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install HTML Validator (tidy)
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Install CSSLint
        run: npm install -g csslint

      - name: Validate HTML files
        run: |
          echo "Validating HTML files..."
          find . -name "*.html" -print0 | xargs -0 -n1 tidy -e -q

      - name: Validate CSS files
        run: |
          echo "Validating CSS files..."
          find . -name "*.css" -print0 | xargs -0 -n1 csslint || true

      - name: Check JavaScript syntax
        run: |
          echo "Checking JavaScript syntax..."
          find . -name "*.js" -print0 | xargs -0 -n1 node -c

      - name: Run SonarCloud Analysis (Java Project)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=fachryghalibi -Dsonar.projectKey=fachryghalibi_tubes-makepal




