name: Continuous Testing by Naufal Ajhar El Hafizh

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  htmltest:
    name: HTML Testing (broken links, missing assets)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install htmltest
        run: |
          curl https://htmltest.wjdp.uk | bash -s -- -b /usr/local/bin

      - name: Run htmltest
        run: htmltest .
